services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/citybikes
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: always
    container_name: citybikes-app
  db:
    image: postgis/postgis
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citybikes
    volumes:
      - ./api/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 15s
      retries: 5
    container_name: db
